project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!myresources/"
    - "!certificate*"
  resources:
    - "files/"
  preview:
    port: 4321
    browser: true

execute:
  # Re-render only when source changes
  freeze: auto

description-meta: "Andreas Handel's personal website."

website:
  title: "Gabriel Santos"
  site-url: "https://www.andreashandel.com"
  repo-url: https://github.com/andreashandel/andreashandelwebsite
  description: "A description for the webpage"
  favicon: /files/icon.png 
  google-analytics: "UA-48442618-4"
  twitter-card: 
    creator: "@anycommonname"
  cookie-consent: false    
  search: true
  navbar:
    background: "#73C6B6"
    logo: /files/logo.png
    right:
     # - text: "About"
     #   file: index.qmd
      - text: "Blog"
        file: posts.qmd
     # - text: "Presentations"
     #   file: presentations.qmd
     # - text: "Projects"
     #   file: projects.qmd
     # - text: "Publications"
     #   file: publications.qmd
      - text: "Projects & Publications"
        file: pubsAll.qmd
      - text: "News"
        file: index.html#featurednews #Basead on the headings created with hashtags "H" 
      # - text: "Subscribe"
      #   file: subscribe.qmd
  


  page-footer:
    left: |
      {{< fa regular copyright >}} Gabriel Santos, 2022<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [these folks.](/posts/quarto-website-migration.html)<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/andreashandel/andreashandelwebsite)


format:
  html:
    theme: 
      light: cosmo
      dark: slate
    css: customstyle.css 
    toc: true
